[[indices-forcemerge]]
== 强制合并

强制合并 API 允许通过 API 强制合并一个或多个索引。合并与 Lucene 索引在每个分片中保存的段的数量相关。强制合并操作允许通过合并它们来减少段的数量。

调用会一直持续到合并完成。期间如果 http 连接丢失，请求将在后台继续执行，并且任何新请求都将被阻塞，直到上一次强制合并完成。

WARNING: 只应针对*只读索引*调用强制合并。针对读写索引运行强制合并可能会导致生成非常大的段（每段大于5Gb），并且除非其主要由已删除的文档组成，否则合并策略将不会考虑再次合并。这可能会导致非常大的段保留在分片中。

[source,js]
--------------------------------------------------
POST /twitter/_forcemerge
--------------------------------------------------
// CONSOLE
// TEST[setup:twitter]

[float]
[[forcemerge-parameters]]
=== 请求参数

强制合并API接受以下请求参数：

[horizontal]
`max_num_segments`:: 要合并的段数。要完全合并索引，请将其设置为`1`。默认只是检查合并是否需要执行，如果是，则执行它。

`only_expunge_deletes`:: 合并过程是否仅删除其中包含删除内容的段。在 Lucene 中，文档不会从段中删除，只是标记为已删除。在段的合并过程中，会创建一个没有这些删除的新段。此标志仅允许合并具有删除的段。默认为 `false`。注意，这不会覆盖 `index.merge.policy.expunge_deletes_allowed` 阈值。


`flush`::  是否应在强制合并后执行刷新。默认为 `true`。

[source,js]
--------------------------------------------------
POST /kimchy/_forcemerge?only_expunge_deletes=false&max_num_segments=100&flush=true
--------------------------------------------------
// CONSOLE
// TEST[s/^/PUT kimchy\n/]

[float]
[[forcemerge-multi-index]]
=== 多索引

强制合并 API 可以将单个调用应用于多个索引，甚至可以应用于 `_all` 索引。每个节点一次在一个分片上执行多索引操作。强制合并会使被合并的分片存储量暂时增加，如果 `max_num_segments` 设置为 `1` ，则存储量将增加一倍，因为所有分片都需要重写为新的分片。

[source,js]
--------------------------------------------------
POST /kimchy,elasticsearch/_forcemerge

POST /_forcemerge
--------------------------------------------------
// CONSOLE
// TEST[s/^/PUT kimchy\nPUT elasticsearch\n/]
