[[indices-shards-stores]]
== 索引分片存储

提供索引分片的存储信息。包括有哪些节点存在分片、分片分配的ID、每个分片的唯一标识符，以及打开分片索引或之前引擎故障时遇到的任何异常。

默认情况下，仅列出具有至少一个未分配的分片的存储信息。当群集健康状态为黄色时，将列出具有至少一个未指派的分片的存储信息。当群集健康状态为红色时，将列出未指派主分片的存储信息，

端点包括特定索引、多个索引或全部索引的分片存储信息：

[source,js]
--------------------------------------------------
# 仅返回索引 test 的信息
GET /test/_shard_stores

# 仅返回索引 test1 和 test2 的信息
GET /test1,test2/_shard_stores

# 返回所有索引信息
GET /_shard_stores
--------------------------------------------------
// CONSOLE
// TEST[s/^/PUT test\nPUT test1\nPUT test2\n/]

可以通过 `status` 参数更改显示存储信息的分片范围。默认为 'yellow' 和 'red'。 'yellow' 列出具有至少一个未指派分片副本的信息，'red' 列出未指派主分片信息。使用 'green' 列出所有已指派拷贝的分片存储信息。

[source,js]
--------------------------------------------------
GET /_shard_stores?status=green
--------------------------------------------------
// CONSOLE
// TEST[setup:node]
// TEST[s/^/PUT my-index\n{"settings":{"number_of_shards":1, "number_of_replicas": 0}}\nPOST my-index\/test\?refresh\n{"test": "test"}\n/]

响应如下：

分片存储信息按索引和分片 ID 分组。

[source,js]
--------------------------------------------------
{
   "indices": {
       "my-index": {
           "shards": {
              "0": { <1>
                "stores": [ <2>
                    {
                        "sPa3OgxLSYGvQ4oPs-Tajw": { <3>
                            "name": "node_t0",
                            "ephemeral_id" : "9NlXRFGCT1m8tkvYCMK-8A",
                            "transport_address": "local[1]",
                            "attributes": {}
                        },
                        "allocation_id": "2iNySv_OQVePRX-yaRH_lQ", <4>
                        "allocation" : "primary|replica|unused" <5>
                        "store_exception": ... <6>
                    }
                ]
              }
           }
       }
   }
}
--------------------------------------------------
// TESTRESPONSE[s/"store_exception": \.\.\.//]
// TESTRESPONSE[s/"sPa3OgxLSYGvQ4oPs-Tajw"/\$node_name/]
// TESTRESPONSE[s/: "[^"]*"/: $body.$_path/]
// TESTRESPONSE[s/"attributes": \{[^}]*\}/"attributes": $body.$_path/]



<1> 分片 ID
<2> 所有分片列表
<3> 节点 ID
<4> 分配 ID
<5> 状态，可以是 primary、replica 或者 unused
<6> 异常信息
