[[indices-stats]]
== 索引统计

索引级统计提供索引上发生的不同操作的统计信息。该 API 提供索引级作用域的统计信息（尽管大多数统计信息也可以使用节点级作用域获得）。

以下返回所有索引的高级聚合和索引级统计信息：

[source,js]
--------------------------------------------------
GET /_stats
--------------------------------------------------
// CONSOLE

可以使用以下方法获得特定索引的统计信息：

[source,js]
--------------------------------------------------
GET /index1,index2/_stats
--------------------------------------------------
// CONSOLE
// TEST[s/^/PUT index1\nPUT index2\n/]

默认情况下，将返回所有统计信息，也可以在 URI 中指定返回特定统计信息。可以是：

[horizontal]
`docs`:: 		文档数/已删除的文档数（尚未合并的文档）。注意，受索引刷新的影响。

`store`:: 		索引的大小。

`indexing`:: 	索引统计信息，可以与逗号分隔 `types` 列表结合使用，以提供文档类型级别的统计信息。

`get`:: 		获取统计信息，包括缺失的统计信息。

`search`:: 		搜索包括建议统计的统计信息。通过添加额外的 `groups` 参数，可以包括自定义组的统计信息（搜索操作可以与一个或多个组关联）。`groups`  参数接受以逗号分隔的组名列表。使用 `_all` 返回所有组的统计信息。

`segments`::    获取打开段的内存使用情况。可设置 `include_segment_file_sizes` 标志，报告每个 lucene 索引文件的总计磁盘使用情况。

`completion`::  完成建议统计。
`fielddata`::   Fielddata 统计
`flush`::       提交统计。
`merge`::       合并统计。
`request_cache`:: <<shard-request-cache,分片请求缓存>> 统计。
`refresh`::     刷新统计。
`warmer`::      热数据统计。
`translog`::    事务日志统计。

一些统计信息可以到字段粒度。其接收由逗号分隔的字段参数列表。默认情况下，包括所有字段：

[horizontal]
`fields`::

    要包含在统计信息中的字段列表。除非提供更具体的字段列表，否则其将作为默认列表（参见下文）。

`completion_fields`::

    要包含在完成建议统计中的字段列表。

`fielddata_fields`::

    要包含在 Fielddata 统计信息中的字段列表。


示例如下：

[source,js]
--------------------------------------------------
# 为所有索引返回合并和刷新的统计信息
GET /_stats/merge,refresh
# 返回索引 my_index 的 type1 和 type2 文档的统计信息
GET /my_index/_stats/indexing?types=type1,type2
# 返回搜索 group1 和 group2 的统计信息
GET /_stats/search?groups=group1,group2
--------------------------------------------------
// CONSOLE
// TEST[s/^/PUT my_index\n/]

使用 `primaries` 和 `total` 聚合，返回的统计数据是在索引级别聚合，其中 `primaries` 是仅主分片的值，而 `total` 则包含了全部主分片和副本分片。

如果要返回分片级别的统计信息，请将 `level` 参数设置为 `shards` 。

注意，当分片在集群中移动时，它们的状态将在其他节点上创建时被清除。另一方面，即使一个分片“脱离”了一个节点，该节点仍将保留分片所贡献的统计信息。

